In [1]:
# Consider the below code to answer further questions:


import numpy as np
list_ = [ '1','2','3','4','5' ]

array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
print(type(list_))

<class 'list'>


In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
print(type(array_list))

<class 'numpy.ndarray'>


The difference is that list_ is the list of python inbuilt data type where as array_list is the ndarray type of numpy 


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [7]:
print("Data Type of list_")
for i in list_:
    print(type(i)," type of element: ",i)

Data Type of list_
<class 'str'>  type of element:  1
<class 'str'>  type of element:  2
<class 'str'>  type of element:  3
<class 'str'>  type of element:  4
<class 'str'>  type of element:  5


In [8]:
print("Data Type of array_list")
for i in array_list:
    print(type(i)," type of element: ",i)

Data Type of array_list
<class 'numpy.str_'>  type of element:  1
<class 'numpy.str_'>  type of element:  2
<class 'numpy.str_'>  type of element:  3
<class 'numpy.str_'>  type of element:  4
<class 'numpy.str_'>  type of element:  5


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list = np.array(object = list_, dtype = int)    

In [10]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
type(array_list)

numpy.ndarray

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans. we defined the dtype of array i.e 'int' thats why the data type of aarray_list is changed into 'int'  shown below the result

In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
# Consider the below code to answer further questions:


import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
num_array.shape    # that means an array cotains 2 rows and 3 columns

(2, 3)

In [17]:
num_array.size     # gives the total numbers of elements present in an array

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
arr= np.zeros((3,3))

In [19]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
print("The Size of Array: ",arr.size)

The Size of Array:  9


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [21]:
identity_mat = np.identity(5)

In [22]:
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])